version: '3.8'

services:
  jamtext:
    image: jamtext:latest
    volumes:
      - jamtext-data:/data/indexes
    environment:
      - INDEX_DIR=/data/indexes
      - CHUNK_SIZE=4096
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./textindex", "-c", "stats"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  jamtext-data:
    driver: local